# Generated by Django 5.2.6 on 2025-09-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
