# Generated by Django 5.1.7 on 2025-11-11 11:12

import apps.auths.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Enter your email address', max_length=255, unique=True, validators=[apps.auths.validators.validate_email_domain], verbose_name='Email Address')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=255, verbose_name='Full Name')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=255, verbose_name='Last Name')),
                ('city', models.CharField(help_text='Enter your city', max_length=255, verbose_name='City')),
                ('country', models.CharField(help_text='Enter your country', max_length=255, verbose_name='Country')),
                ('departament', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], default='IT', help_text='Enter your departament', max_length=255, verbose_name='Departament')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('manager', 'Manager')], default='user', help_text='Enter your role', max_length=50, verbose_name='Role')),
                ('birth_date', models.DateField(blank=True, help_text='Enter your birth date', null=True, verbose_name='Birth Date')),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='Enter your salary', max_digits=10, verbose_name='Salary')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
