# Generated by Django 5.1.7 on 2025-11-11 16:38

import apps.auths.validators
import django.contrib.auth.password_validation
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='departament',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], default='IT', help_text='Department within the company', max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's date of birth (optional)", null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(help_text='City where the user resides', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(help_text="User's country of residence", max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the user joined the system', verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Unique email address used for authentication', max_length=255, unique=True, validators=[apps.auths.validators.validate_email_domain], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text="User's given name", max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text='First name + Last name', max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user is active', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether this user can access the admin site', verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='The last time the user logged in', null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text="User's family name", max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='Must meet Django password validation requirements', max_length=128, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', help_text="User's role in the organization", max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="User's monthly salary", max_digits=10, verbose_name='Salary'),
        ),
    ]
